### ISSUE TITLE
Add a confidence metric of some sort for the geostring -> lat/long transform

### ISSUE THREAD

**Issue by kbrose** [chicago-justice-project/article-tagging#102]

**Comment by kbrose** [comment]
`gisgraphy` returns a score but it's kind of confusing (documentation: https://www.gisgraphy.com/documentation/user-guide.php#geocodingservice)

They also return a numFound in the JSON which might be more useful?

**Comment by jherzberg** [comment]
To use gisgraphy in ipython - 

```
def gisgraphy_addr(addr):
    joined = '+'.join(addr.split(' '))
    headers = {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'en-US,en;q=0.5', 'Connection': 'keep-alive', 'DNT': '1', 'Host':'services.gisgraphy.com', 'Upgrade-Insecure-Requests': '1', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0'}
    url = 'https://services.gisgraphy.com/geocoding/?address={}%2C+&limitnbresult=1&format=json'.format(joined)
    r = requests.get(url, headers=headers)
    if r.status_code == 200:
        return r.json()
    else:
        print('ERROR: {}'.format(r.status_code))
```

**Comment by jherzberg** [comment]
I think numFound is somewhat informative. Some examples I got: 
5500 S University Ave: 26
5500 S University Ave Chicago: 1
thighs: 1
thighs Chicago: 0
600 S State Street: 3
600 S State Street Chicago IL: 3

Not always:
151 N Michigan Ave: 8
151 N Michigan Ave Chicago: 10
thighs Chicago, IL: 9

**Comment by jherzberg** [comment]
'nonsense, Chicago IL' and 'thighs, Chicago IL' return 46.921287536621094, -104.0040054321289 which is in North Dakota. Ergo, we should dump anything with these lat longs.

**Comment by brandonjyee** [comment]
https://github.com/gisgraphy/gisgraphy/blob/master/etc/solrtemplates.txt

- Shows some solr queries that use boosting on queries (i.e. weighting the score in favor of matches on certain fields, such as matching a city is weighted higher). The caret "^" symbol is for boosting. Don't know if they do boosting on the indexing side. But the boosting affects the relevancy score. 
- Still not sure how scores compare across different queries such as:
     1. Is there a scoring threshold that would indicate the result is not reliable? Like if score is > 20, maybe that means it's not a reliable score.
     2. Can scores be compared across different queries and if so, can we rely on a quantitative difference? Like if "hello, Chicago" has a score of 20 for its first result, and "world, Chicago" has a score of 5 for its first result, does that mean "world, Chicago" is 4x more relevant match to its result than "hello, Chicago" to its first result?

**Comment by kbrose** [comment]
In summary, we are going forward w/ a comparison between scores from raw geostring and post processed geostrings, along with the numFound attribute. In addition, an investigation into how many times any particular lat/long pair occur will probably be indicative of problems (if it can't be geocoded well, it'll get shoved into the exact center of chicago for example).

Closing for now since I think we're in a good place here. Thanks for the help @jherzberg and @brandonjyee (especially w/ the help digging into gisgraphy's codebase!)
