### ISSUE TITLE
Handle words missing from word vectorization better

### ISSUE THREAD

**Issue by kbrose** [chicago-justice-project/article-tagging#105]
This caused an error in the batch processing.

`KeyError: "None of [['[Take', 'Our', 'Poll][1]', '[1]:', 'http://polldaddy.com/poll/6009092']] are in the [index]"`

**Comment by meshulam** [comment]
This error with markdown links is the only issue I've seen in the backfill. looks like it's when the entirety of the article body is just a link: 

```
[Take Our Poll][1]

   [1]: http://polldaddy.com/poll/7514301
```
http://data.chicagojustice.org/admin/newsarticles/article/131973/change/
