### ISSUE TITLE
Semantic word vectorizer

### ISSUE THREAD

**Issue by kbrose** [chicago-justice-project/article-tagging#22]
Are there easy-to-use, pre-trained, cross-platform word vectorizers? Preferably with a python interface?

**Comment by kbrose** [comment]
I think I may be an idiot. Isn't a pre-trained word vectorizer literally just a set of `(word, [vector])` pairs...?

**Comment by jherzberg** [comment]
Is [this](http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html) what you're looking for?

**Comment by kbrose** [comment]
Yeah I wasn't really clear, I meant a semantic word vectorizer. Something like what's discussed here: https://www.tensorflow.org/tutorials/word2vec

**Comment by kbrose** [comment]
https://github.com/mmihaltz/word2vec-GoogleNews-vectors

**Comment by kbrose** [comment]
https://github.com/kbrose/article-tagging/blob/word2vec/lib/notebooks/word2vec-experiments.ipynb

**Comment by kbrose** [comment]
So it looks like GloVe is a lot more user friendly. Looking through https://github.com/stanfordnlp/GloVe at the moment.

**Comment by kbrose** [comment]
A GloVe dataset loader has since been incorporated and seems to be working fairly well for the geo-string extraction.
