### ISSUE TITLE
Capturing incident times

### ISSUE THREAD

**Issue by pandey** [chicago-justice-project/article-tagging#33]
Would the project find any value in capturing incident times associated with location information in news articles? I'm working on address extraction and it would be a small effort to annotate related time data in the test corpus.

**Comment by kbrose** [comment]
If it's a small effort and it's accurate then yeah, can't go wrong with more, good quality data. Keep in mind that we do have the date/time the article was published, which in most (but not all!) cases will be quite close temporally to the incident time.

**Comment by kbrose** [comment]
Closing since this is currently out of scope.
