### ISSUE TITLE
Error creating 'fpr', 'tpr', 'ppv' dataframes from bench_results

### ISSUE THREAD

**Issue by m00nd00r** [chicago-justice-project/article-tagging#37]
While trying to create the model locally in bag-of-words-count-stemmed-binary.ipynb at this code block:

```
fpr = pd.DataFrame(bench_results['fpr'], columns=crime_df.columns.values[9:]).T

tpr = pd.DataFrame(bench_results['tpr'], columns=crime_df.columns.values[9:]).T

ppv = pd.DataFrame(bench_results['ppv'], columns=crime_df.columns.values[9:]).T

```

I get the following error:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/anaconda/envs/cjp-ap/lib/python3.6/site-packages/pandas/core/internals.py in create_block_manager_from_blocks(blocks, axes)
   4293                 blocks = [make_block(values=blocks[0],
-> 4294                                      placement=slice(0, len(axes[0])))]
   4295 

~/anaconda/envs/cjp-ap/lib/python3.6/site-packages/pandas/core/internals.py in make_block(values, placement, klass, ndim, dtype, fastpath)
   2718 
-> 2719     return klass(values, ndim=ndim, fastpath=fastpath, placement=placement)
   2720 

~/anaconda/envs/cjp-ap/lib/python3.6/site-packages/pandas/core/internals.py in __init__(self, values, placement, ndim, fastpath)
    114                              'implies %d' % (len(self.values),
--> 115                                              len(self.mgr_locs)))
    116 

ValueError: Wrong number of items passed 38, placement implies 41

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-9-ebe221ecd067> in <module>()
----> 1 fpr = pd.DataFrame(bench_results['fpr'], columns=crime_df.columns.values[9:]).T
      2 
      3 tpr = pd.DataFrame(bench_results['tpr'], columns=crime_df.columns.values[9:]).T
      4 
      5 ppv = pd.DataFrame(bench_results['ppv'], columns=crime_df.columns.values[9:]).T

~/anaconda/envs/cjp-ap/lib/python3.6/site-packages/pandas/core/frame.py in __init__(self, data, index, columns, dtype, copy)
    304             else:
    305                 mgr = self._init_ndarray(data, index, columns, dtype=dtype,
--> 306                                          copy=copy)
    307         elif isinstance(data, (list, types.GeneratorType)):
    308             if isinstance(data, types.GeneratorType):

~/anaconda/envs/cjp-ap/lib/python3.6/site-packages/pandas/core/frame.py in _init_ndarray(self, values, index, columns, dtype, copy)
    481             values = maybe_infer_to_datetimelike(values)
    482 
--> 483         return create_block_manager_from_blocks([values], [columns, index])
    484 
    485     @property

~/anaconda/envs/cjp-ap/lib/python3.6/site-packages/pandas/core/internals.py in create_block_manager_from_blocks(blocks, axes)
   4301         blocks = [getattr(b, 'values', b) for b in blocks]
   4302         tot_items = sum(b.shape[0] for b in blocks)
-> 4303         construction_error(tot_items, blocks[0].shape[1:], axes, e)
   4304 
   4305 

~/anaconda/envs/cjp-ap/lib/python3.6/site-packages/pandas/core/internals.py in construction_error(tot_items, block_shape, axes, e)
   4278         raise ValueError("Empty data passed with indices specified.")
   4279     raise ValueError("Shape of passed values is {0}, indices imply {1}".format(
-> 4280         passed, implied))
   4281 
   4282 

ValueError: Shape of passed values is (38, 4), indices imply (41, 4)

I did manage to run the model successfully before using the new database files. However, even when I try running the previous database subsequently, I get the exact same problem.

Any ideas as to how to resolve this? 

Before submitting this issue, I have since deleted and re-cloned this repo, then setup, and re-run this notebook three times. I'm working on mac OSX. And finally, when I run the tagnews.test() from the command line that fails - if that helps.

**Comment by kbrose** [comment]
Most recent commit should handle it. There were 2 tags added in the most recent pull of the data dump that threw off some of the loading code. Let me know if things are still broken.
