### ISSUE TITLE
Find a good NER corpus to use as training data

### ISSUE THREAD

**Issue by kbrose** [chicago-justice-project/article-tagging#62]
**N**amed **E**ntity **R**ecognition describes a superset of what we are trying to do w/ the location extraction. It is also a well studied field, so there are probably open corpora that have labeled data we could use to augment (or use exclusively as) our training data.

We should do some investigating to try and find such a corpus.

**Comment by jherzberg** [comment]
https://www.kaggle.com/abhinavwalia95/entity-annotated-corpus/data (Has ~60,000 geo-entities).
http://www.cs.technion.ac.il/~gabr/resources/data/ne_datasets.html (List of 13 such datasets)

**Comment by kbrose** [comment]
https://old.datahub.io/dataset/reuters-128-nif-ner-corpus

http://www.opener-project.eu/project/performance/

https://github.com/EuropeanaNewspapers/ner-corpora (do they have anything in english....?)

https://cogcomp.org/page/resource_view/81

**Comment by kbrose** [comment]
https://depends-on-the-definition.com/named-entity-recognition-conditional-random-fields-python/

**Comment by kbrose** [comment]
http://nlpforhackers.io/named-entity-extraction/ has simple code to load the GMB dataset (http://gmb.let.rug.nl/data.php)

**Comment by fgregg** [comment]
How about wikipedia: https://opendata.stackexchange.com/questions/11961/corpus-of-english-text-with-tagged-locations/11972#11972

**Comment by kbrose** [comment]
Closing this b/c (a) the kaggle dataset is pretty good, and (b) we have "enough" data to break into training/validation datasets of reasonable size.
