### ISSUE TITLE
Create a function to get lat/long values from list of geo-strings.

### ISSUE THREAD

**Issue by kbrose** [chicago-justice-project/article-tagging#74]
Related to #72.

Function signature should approximate

```python
>>> lat_longs = lat_longs_from_geo_strings(['1700 block of south halsted', 'merchandise mart'])
>>> print(lat_longs)
[[12.345, 67.890], [98.76, 54.321]]
```

Some installation instructions for whatever API is being used will also be needed.

**Comment by jherzberg** [comment]
[Geocoder](https://geocoder.readthedocs.io/) works sufficiently and without a key. I'll set up a function around it to do what you requested above. It should be noted though that PyPi says the build is failing and coverage is 54%.

**Comment by kbrose** [comment]
Notebooks previously made by John:
https://github.com/chicago-justice-project/article-tagging/blob/master/lib/notebooks/geocode.ipynb 
https://github.com/chicago-justice-project/article-tagging/blob/master/lib/notebooks/geotag.ipynb
